name: Build Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Zip All Top-Level Folders Except .github
        run: |
          mkdir content_temp
          for dir in */ ; do
            if [[ "$dir" != ".github/" ]]; then
              cp -r "$dir" content_temp/
            fi
          done
          zip -r content.zip content_temp

      - name: Upload Content Package
        uses: actions/upload-artifact@v4
        with:
          name: content-package
          path: content.zip
