name: Build Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version number (e.g. 1.0.0)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      RELEASE_TAG: ${{ github.event.inputs.tag != '' && github.event.inputs.tag || github.ref_name }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Prepare Content
        run: |
          mkdir content_temp
          for dir in */ ; do
            # Skip .github and content_temp itself
            if [[ "$dir" != ".github/" && "$dir" != "content_temp/" ]]; then
              cp -r "$dir" content_temp/
            fi
          done
          zip -r content.zip build/

      - name: Create Git Tag (if workflow_dispatch)
        id: tag_version
        if: github.event_name == 'workflow_dispatch'
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.ACTIONS_PAT }}
          custom_tag: ${{ env.RELEASE_TAG }}

      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          token: ${{ secrets.ACTIONS_PAT }}

      - name: Upload Release Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: content.zip
          asset_name: content.zip
          asset_content_type: application/zip